language: ruby

rvm:
  - 2.1.5

sudo: false
cache:
  bundler: true
  directories:
    - app/assets/images

branches:
  only:
    - 'master'
    - 'develop'

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres  
before_install: gem install bundler
bundler_args: "--deployment --without development production --with postgresql --jobs 3 --retry 3"

notifications:
  irc:
    channels:
      - "irc.freenode.org:6667#sitesupportDev"
    template:
      - "%{repository_slug}#%{commit} (%{branch} - %{commit_subject}): %{message} %{build_url}"
