development:
  adapter: postgresql
  database: sitesupportDev
  encoding: unicode
  pool: 16
  username: su
  password: su
  host: localhost

test:
  adapter: postgresql
  database: travis_ci_test

production:
  adapter: postgresql
  database: sitesupport
  pool: 16
  encoding: su
  username: su
  password: su
  host: localhost

cucumber:
  <<: *TEST
